### ISSUE TITLE
Missing tests for large spaces and empty lines.

### ISSUE THREAD

**Issue by Estecka** [Glagan/42-exam-rank-03#1]
The project for minipaint (and presumably micropaint) allows valid operation files to contain empty lines, and properties to be separated by more than one space.

While the `our_mini_paint` provided in this repo does respects these constraints, the test generator does not seem to test for it:

As of writting, my minipaint fails if it find an empty line or multiple spaces in a row. Yet the tester has sent it through thousands of tests without detecting the issue.

Here's an example of file that should be tested, but is not:
```
20 20 .
C 4 4 4      v

c 10 10   10 m
```

**Comment by Glagan** [comment]
I added random spaces between lines.

But for spaces between properties, the subject says:

>There must be one space between each variable in a line

So, I don't know if you should handle spaces between them, maybe it depends on the ``fprintf`` implementation and your platform, or maybe the subject changed.  
If you still want to test with it, I added them in another branch [https://github.com/Glagan/42-exam-rank-03/tree/space_between_properties](https://github.com/Glagan/42-exam-rank-03/tree/space_between_properties).

**Comment by Estecka** [comment]
I attempted the exam today; I'm certain the subject said `at least one space`. So yes, it must have changed.

I'll have a look at it tomorrow, thank you.

**Comment by Glagan** [comment]
If the new subject says so, I pushed it to master.
